-- SoraList shared-data schema for Supabase.
-- Authentication credentials remain in auth.users; this schema stores app data only.

begin;

create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (username ~ '^[A-Za-z0-9_]{3,24}$'),
  display_name text check (char_length(display_name) <= 80),
  bio text not null default '' check (char_length(bio) <= 500),
  avatar_url text,
  region text not null default 'US' check (region ~ '^[A-Z]{2}$'),
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index profiles_username_case_insensitive_idx
  on public.profiles (lower(username));

create table public.anime_list_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  anime_id bigint not null,
  status text not null default 'plan' check (status in ('plan', 'watching', 'completed', 'paused', 'dropped')),
  episodes_watched integer not null default 0 check (episodes_watched >= 0),
  rating numeric(3,1) check (rating is null or (rating >= 1 and rating <= 5)),
  snapshot jsonb not null default '{}'::jsonb,
  added_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, anime_id)
);

create index anime_list_entries_anime_id_idx on public.anime_list_entries (anime_id);

create table public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  check (requester_id <> recipient_id),
  unique (requester_id, recipient_id)
);

create index friend_requests_recipient_idx on public.friend_requests (recipient_id, created_at desc);

create table public.friendships (
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_a, user_b),
  check (user_a::text < user_b::text)
);

create index friendships_user_b_idx on public.friendships (user_b);

-- A rejection is private to the person who rejected the request. The sender cannot read it.
create table public.rejected_friend_requests (
  owner_id uuid not null references public.profiles(id) on delete cascade,
  rejected_user_id uuid not null references public.profiles(id) on delete cascade,
  rejected_at timestamptz not null default now(),
  primary key (owner_id, rejected_user_id),
  check (owner_id <> rejected_user_id)
);

create table public.groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 60),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create index group_members_user_idx on public.group_members (user_id);

create table public.group_anime_entries (
  group_id uuid not null references public.groups(id) on delete cascade,
  anime_id bigint not null,
  snapshot jsonb not null default '{}'::jsonb,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (group_id, anime_id)
);

create table public.group_anime_interests (
  group_id uuid not null,
  anime_id bigint not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (group_id, anime_id, user_id),
  foreign key (group_id, anime_id)
    references public.group_anime_entries(group_id, anime_id) on delete cascade
);

create index group_anime_interests_user_idx on public.group_anime_interests (user_id);

create table public.group_messages (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 500),
  system boolean not null default false,
  created_at timestamptz not null default now()
);

create index group_messages_group_created_idx on public.group_messages (group_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger anime_list_entries_set_updated_at
before update on public.anime_list_entries
for each row execute function public.set_updated_at();

create trigger groups_set_updated_at
before update on public.groups
for each row execute function public.set_updated_at();

create trigger group_anime_entries_set_updated_at
before update on public.group_anime_entries
for each row execute function public.set_updated_at();

create or replace function public.sync_completed_episode_progress()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  total_episodes integer;
begin
  if new.status = 'plan' then
    new.episodes_watched := 0;
  elsif new.status = 'completed' and coalesce(new.snapshot->>'episodes', '') ~ '^[0-9]+$' then
    total_episodes := (new.snapshot->>'episodes')::integer;
    if total_episodes > 0 then
      new.episodes_watched := total_episodes;
    end if;
  end if;
  return new;
end;
$$;

create trigger anime_list_entries_sync_progress
before insert or update of status, episodes_watched, snapshot on public.anime_list_entries
for each row execute function public.sync_completed_episode_progress();

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  base_name text;
  candidate text;
  attempt integer := 0;
begin
  base_name := lower(regexp_replace(
    coalesce(
      nullif(new.raw_user_meta_data->>'user_name', ''),
      nullif(new.raw_user_meta_data->>'preferred_username', ''),
      nullif(new.raw_user_meta_data->>'global_name', ''),
      nullif(new.raw_user_meta_data->>'full_name', ''),
      nullif(split_part(new.email, '@', 1), ''),
      'user'
    ),
    '[^A-Za-z0-9_]+', '_', 'g'
  ));
  base_name := trim(both '_' from base_name);
  if char_length(base_name) < 3 then
    base_name := 'user';
  end if;
  base_name := left(base_name, 16);
  candidate := base_name;

  while exists (select 1 from public.profiles where lower(username) = lower(candidate)) loop
    attempt := attempt + 1;
    candidate := left(base_name, 16) || '_' || left(replace(new.id::text, '-', ''), 6) ||
      case when attempt > 1 then attempt::text else '' end;
    candidate := left(candidate, 24);
  end loop;

  insert into public.profiles (id, username, display_name, avatar_url)
  values (
    new.id,
    candidate,
    left(coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', candidate), 80),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture')
  );
  return new;
end;
$$;

create trigger auth_user_created_create_profile
after insert on auth.users
for each row execute function public.create_profile_for_new_user();

create or replace function public.are_friends(first_user uuid, second_user uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.friendships friendship
    where friendship.user_a = least(first_user, second_user)
      and friendship.user_b = greatest(first_user, second_user)
  );
$$;

create or replace function public.is_group_member(target_group uuid, target_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.group_members membership
    where membership.group_id = target_group and membership.user_id = target_user
  );
$$;

create or replace function public.send_friend_request(target_username text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id uuid;
  new_request_id uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  select profile.id into target_id
  from public.profiles profile
  where lower(profile.username) = lower(btrim(target_username));

  if target_id is null then raise exception 'Username not found'; end if;
  if target_id = auth.uid() then raise exception 'You cannot add yourself'; end if;
  if public.are_friends(auth.uid(), target_id) then raise exception 'You are already friends'; end if;
  if exists (
    select 1 from public.friend_requests request
    where (request.requester_id = auth.uid() and request.recipient_id = target_id)
       or (request.requester_id = target_id and request.recipient_id = auth.uid())
  ) then raise exception 'A request already exists'; end if;

  insert into public.friend_requests (requester_id, recipient_id)
  values (auth.uid(), target_id)
  returning id into new_request_id;

  delete from public.rejected_friend_requests
  where owner_id = auth.uid() and rejected_user_id = target_id;
  return new_request_id;
end;
$$;

create or replace function public.respond_to_friend_request(request_id uuid, accept_request boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_record public.friend_requests%rowtype;
begin
  select * into request_record
  from public.friend_requests
  where id = request_id and recipient_id = auth.uid()
  for update;

  if request_record.id is null then raise exception 'Friend request not found'; end if;

  if accept_request then
    insert into public.friendships (user_a, user_b)
    values (least(request_record.requester_id, request_record.recipient_id), greatest(request_record.requester_id, request_record.recipient_id))
    on conflict do nothing;
    delete from public.rejected_friend_requests
    where (owner_id = request_record.requester_id and rejected_user_id = request_record.recipient_id)
       or (owner_id = request_record.recipient_id and rejected_user_id = request_record.requester_id);
  else
    insert into public.rejected_friend_requests (owner_id, rejected_user_id)
    values (auth.uid(), request_record.requester_id)
    on conflict (owner_id, rejected_user_id)
    do update set rejected_at = now();
  end if;

  delete from public.friend_requests where id = request_record.id;
end;
$$;

create or replace function public.cancel_friend_request(request_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.friend_requests where id = request_id and requester_id = auth.uid();
$$;

create or replace function public.remove_friend(friend_username text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  friend_id uuid;
begin
  select id into friend_id from public.profiles where lower(username) = lower(btrim(friend_username));
  if friend_id is null then return; end if;
  delete from public.friendships
  where user_a = least(auth.uid(), friend_id) and user_b = greatest(auth.uid(), friend_id);
end;
$$;

create or replace function public.set_group_anime_interest(
  target_group uuid,
  target_anime bigint,
  anime_snapshot jsonb,
  interested boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not public.is_group_member(target_group, auth.uid()) then
    raise exception 'You are not a member of this group';
  end if;

  if interested then
    insert into public.group_anime_entries (group_id, anime_id, snapshot, created_by)
    values (target_group, target_anime, coalesce(anime_snapshot, '{}'::jsonb), auth.uid())
    on conflict (group_id, anime_id)
    do update set snapshot = excluded.snapshot;

    insert into public.group_anime_interests (group_id, anime_id, user_id)
    values (target_group, target_anime, auth.uid())
    on conflict do nothing;
  else
    delete from public.group_anime_interests
    where group_id = target_group and anime_id = target_anime and user_id = auth.uid();

    delete from public.group_anime_entries entry
    where entry.group_id = target_group
      and entry.anime_id = target_anime
      and not exists (
        select 1 from public.group_anime_interests interest
        where interest.group_id = entry.group_id and interest.anime_id = entry.anime_id
      );
  end if;
end;
$$;

alter table public.profiles enable row level security;
alter table public.anime_list_entries enable row level security;
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
alter table public.rejected_friend_requests enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_anime_entries enable row level security;
alter table public.group_anime_interests enable row level security;
alter table public.group_messages enable row level security;

create policy profiles_read_authenticated on public.profiles
for select to authenticated using (true);
create policy profiles_insert_self on public.profiles
for insert to authenticated with check (id = (select auth.uid()));
create policy profiles_update_self on public.profiles
for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));

create policy list_entries_read_self_or_friend on public.anime_list_entries
for select to authenticated using (
  user_id = (select auth.uid()) or public.are_friends((select auth.uid()), user_id)
);
create policy list_entries_insert_self on public.anime_list_entries
for insert to authenticated with check (user_id = (select auth.uid()));
create policy list_entries_update_self on public.anime_list_entries
for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy list_entries_delete_self on public.anime_list_entries
for delete to authenticated using (user_id = (select auth.uid()));

create policy friend_requests_read_participant on public.friend_requests
for select to authenticated using (
  requester_id = (select auth.uid()) or recipient_id = (select auth.uid())
);
create policy friendships_read_participant on public.friendships
for select to authenticated using (
  user_a = (select auth.uid()) or user_b = (select auth.uid())
);
create policy rejected_requests_read_owner on public.rejected_friend_requests
for select to authenticated using (owner_id = (select auth.uid()));

create policy groups_read_member_or_owner on public.groups
for select to authenticated using (
  owner_id = (select auth.uid()) or public.is_group_member(id, (select auth.uid()))
);
create policy groups_insert_owner on public.groups
for insert to authenticated with check (owner_id = (select auth.uid()));
create policy groups_update_owner on public.groups
for update to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy groups_delete_owner on public.groups
for delete to authenticated using (owner_id = (select auth.uid()));

create policy group_members_read_member_or_owner on public.group_members
for select to authenticated using (
  public.is_group_member(group_id, (select auth.uid()))
  or exists (select 1 from public.groups target where target.id = group_id and target.owner_id = (select auth.uid()))
);
create policy group_members_insert_owner_for_friend on public.group_members
for insert to authenticated with check (
  exists (select 1 from public.groups target where target.id = group_id and target.owner_id = (select auth.uid()))
  and (user_id = (select auth.uid()) or public.are_friends((select auth.uid()), user_id))
);
create policy group_members_delete_owner_or_self on public.group_members
for delete to authenticated using (
  user_id = (select auth.uid())
  or exists (select 1 from public.groups target where target.id = group_id and target.owner_id = (select auth.uid()))
);

create policy group_anime_entries_read_member on public.group_anime_entries
for select to authenticated using (public.is_group_member(group_id, (select auth.uid())));
create policy group_anime_entries_insert_member on public.group_anime_entries
for insert to authenticated with check (
  created_by = (select auth.uid()) and public.is_group_member(group_id, (select auth.uid()))
);
create policy group_anime_entries_update_member on public.group_anime_entries
for update to authenticated using (public.is_group_member(group_id, (select auth.uid())))
with check (public.is_group_member(group_id, (select auth.uid())));
create policy group_anime_entries_delete_member on public.group_anime_entries
for delete to authenticated using (public.is_group_member(group_id, (select auth.uid())));

create policy group_anime_interests_read_member on public.group_anime_interests
for select to authenticated using (public.is_group_member(group_id, (select auth.uid())));
create policy group_anime_interests_insert_self on public.group_anime_interests
for insert to authenticated with check (
  user_id = (select auth.uid()) and public.is_group_member(group_id, (select auth.uid()))
);
create policy group_anime_interests_delete_self on public.group_anime_interests
for delete to authenticated using (user_id = (select auth.uid()));

create policy group_messages_read_member on public.group_messages
for select to authenticated using (public.is_group_member(group_id, (select auth.uid())));
create policy group_messages_insert_member on public.group_messages
for insert to authenticated with check (
  author_id = (select auth.uid())
  and not system
  and public.is_group_member(group_id, (select auth.uid()))
);

revoke all on all tables in schema public from anon;
grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.anime_list_entries to authenticated;
grant select on public.friend_requests, public.friendships, public.rejected_friend_requests to authenticated;
grant select, insert, update, delete on public.groups to authenticated;
grant select, insert, delete on public.group_members to authenticated;
grant select, insert, update, delete on public.group_anime_entries to authenticated;
grant select, insert, delete on public.group_anime_interests to authenticated;
grant select, insert on public.group_messages to authenticated;
grant usage, select on sequence public.anime_list_entries_id_seq to authenticated;

revoke all on function public.send_friend_request(text) from public;
revoke all on function public.respond_to_friend_request(uuid, boolean) from public;
revoke all on function public.cancel_friend_request(uuid) from public;
revoke all on function public.remove_friend(text) from public;
revoke all on function public.set_group_anime_interest(uuid, bigint, jsonb, boolean) from public;
revoke all on function public.are_friends(uuid, uuid) from public;
revoke all on function public.is_group_member(uuid, uuid) from public;
grant execute on function public.send_friend_request(text) to authenticated;
grant execute on function public.respond_to_friend_request(uuid, boolean) to authenticated;
grant execute on function public.cancel_friend_request(uuid) to authenticated;
grant execute on function public.remove_friend(text) to authenticated;
grant execute on function public.set_group_anime_interest(uuid, bigint, jsonb, boolean) to authenticated;
grant execute on function public.are_friends(uuid, uuid) to authenticated;
grant execute on function public.is_group_member(uuid, uuid) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy avatar_upload_own_folder on storage.objects
for insert to authenticated with check (
  bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text
);
create policy avatar_update_own_folder on storage.objects
for update to authenticated using (
  bucket_id = 'avatars' and owner_id = (select auth.uid()::text)
) with check (
  bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text
);
create policy avatar_delete_own_folder on storage.objects
for delete to authenticated using (
  bucket_id = 'avatars' and owner_id = (select auth.uid()::text)
);

alter table public.profiles replica identity full;
alter table public.anime_list_entries replica identity full;
alter table public.friend_requests replica identity full;
alter table public.friendships replica identity full;
alter table public.rejected_friend_requests replica identity full;
alter table public.groups replica identity full;
alter table public.group_members replica identity full;
alter table public.group_anime_entries replica identity full;
alter table public.group_anime_interests replica identity full;
alter table public.group_messages replica identity full;

do $$
declare
  table_name text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach table_name in array array[
      'profiles', 'anime_list_entries', 'friend_requests', 'friendships',
      'rejected_friend_requests', 'groups', 'group_members',
      'group_anime_entries', 'group_anime_interests', 'group_messages'
    ] loop
      if not exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = table_name
      ) then
        execute format('alter publication supabase_realtime add table public.%I', table_name);
      end if;
    end loop;
  end if;
end;
$$;

commit;
